name: Apply

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  packages: write

concurrency:
  group: website-terraform
  cancel-in-progress: false

jobs:
  terraform:
    uses: KandlerLi/gha-common/.github/workflows/terraform-apply.yml@v0.0.13
    with:
      aws_region: eu-central-1
      post_apply_command: |
        aws s3 sync site/ "s3://$(terraform output -raw bucket_name)" --delete
        aws cloudfront create-invalidation \
          --distribution-id "$(terraform output -raw distribution_id)" \
          --paths '/*'
    secrets: inherit
