name: Checks

on:
  pull_request:
  workflow_dispatch:

jobs:
  terraform:
    uses: KandlerLi/gha-common/.github/workflows/terraform-checks.yml@v0.0.13
    with:
      aws_region: eu-central-1
      extra_repo_vars: "ROUTE53_ZONE_ID"
    secrets: inherit
    permissions:
      contents: read
      id-token: write
      packages: write
